import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { LocationAutocompleteController, createBrowserClock } from '../src/location/autocomplete-controller.js';
import { LocationAutocompleteDomBinding } from '../src/location/autocomplete-dom-binding.js';
import { DevelopmentLocationProvider, resolveTimezone } from '../src/location/providers.js';

function domFixture() {
  const dom = new JSDOM(`<label class="location-search"><input id="search"></label><div id="results"></div><input id="city"><input id="state"><input id="country"><input id="latitude"><input id="longitude"><input id="timezone"><input id="placeId">`);
  const document = dom.window.document; return { dom, document, input: document.querySelector('#search'), results: document.querySelector('#results') };
}

function createHarness({ provider = new DevelopmentLocationProvider(), debounceMs = 0 } = {}) {
  const fixture = domFixture(); let selectedPlace = null;
  const render = (state) => { fixture.results.innerHTML = state.status === 'error' ? `<p class="error">${state.error.message}</p>` : state.status === 'empty' ? '<p>No matching development locations</p>' : state.results.map((item, index) => `<button data-location-index="${index}" class="${index === state.activeIndex ? 'active' : ''}">${item.city}</button>`).join(''); };
  const controller = new LocationAutocompleteController({ provider, debounceMs, clock: createBrowserClock(fixture.dom.window), onState: render });
  const select = async (place) => { selectedPlace = place; fixture.document.querySelector('#city').value = place.city; fixture.document.querySelector('#state').value = place.state; fixture.document.querySelector('#country').value = place.country; fixture.document.querySelector('#latitude').value = String(place.latitude); fixture.document.querySelector('#longitude').value = String(place.longitude); fixture.document.querySelector('#timezone').value = resolveTimezone(place.latitude, place.longitude); fixture.document.querySelector('#placeId').value = place.placeId; controller.escape(); };
  const binding = new LocationAutocompleteDomBinding({ input: fixture.input, results: fixture.results, documentTarget: fixture.document, controller, onQueryChanged: () => { selectedPlace = null; }, onSelect: select });
  return { ...fixture, controller, binding, select, selected: () => selectedPlace, close: () => { binding.destroy(); fixture.dom.window.close(); } };
}

const wait = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
async function type(harness, value) { harness.input.value = value; harness.input.dispatchEvent(new harness.dom.window.Event('input', { bubbles: true })); await wait(10); }

test('previous receiver-changing timer call reproduces Illegal invocation and wrapped clock does not', () => { const nativeClock = { clearTimeout(id) { if (this !== nativeClock) throw new TypeError('Illegal invocation'); return id; }, setTimeout(callback) { if (this !== nativeClock) throw new TypeError('Illegal invocation'); callback(); return 1; } }; const legacyControllerShape = { cancel: nativeClock.clearTimeout }; assert.throws(() => legacyControllerShape.cancel(1), /Illegal invocation/); const controller = new LocationAutocompleteController({ provider: { search: async () => [] }, clock: nativeClock }); assert.doesNotThrow(() => controller.input('Del')); controller.destroy(); });
test('bound input API can be invoked as a callback without losing controller context', () => { const calls = []; const clock = { setTimeout(callback) { calls.push(callback); return 1; }, clearTimeout() {} }; const controller = new LocationAutocompleteController({ provider: { search: async () => [] }, clock }); const callback = controller.input; assert.doesNotThrow(() => callback('Del')); assert.equal(calls.length, 1); controller.destroy(); });
test('browser timer wrapper executes debounce and Del renders Delhi', async () => { const harness = createHarness(); await type(harness, 'Del'); assert.match(harness.results.textContent, /Delhi/); harness.close(); });
test('pointer selection fills all profile fields and timezone', async () => { const harness = createHarness(); await type(harness, 'Del'); harness.results.querySelector('button').dispatchEvent(new harness.dom.window.Event('pointerdown', { bubbles: true, cancelable: true })); await wait(0); assert.equal(harness.selected().city, 'Delhi'); assert.equal(harness.document.querySelector('#city').value, 'Delhi'); assert.equal(harness.document.querySelector('#state').value, 'Delhi'); assert.equal(harness.document.querySelector('#country').value, 'India'); assert.equal(harness.document.querySelector('#latitude').value, '28.6139'); assert.equal(harness.document.querySelector('#longitude').value, '77.209'); assert.equal(harness.document.querySelector('#timezone').value, 'Asia/Kolkata'); assert.equal(harness.document.querySelector('#placeId').value, 'mock-delhi'); harness.close(); });
test('arrow keys move active result, Enter selects, and Escape closes', async () => { const harness = createHarness(); await type(harness, 'India'); const initial = harness.controller.current().city; harness.input.dispatchEvent(new harness.dom.window.KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true })); assert.notEqual(harness.controller.current().city, initial); harness.input.dispatchEvent(new harness.dom.window.KeyboardEvent('keydown', { key: 'Enter', bubbles: true })); await wait(0); assert.ok(harness.selected()); await type(harness, 'Del'); harness.input.dispatchEvent(new harness.dom.window.KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); assert.equal(harness.results.textContent, ''); harness.close(); });
test('typing after selection clears selected identity', async () => { const harness = createHarness(); await type(harness, 'Del'); await harness.select(harness.controller.current()); assert.ok(harness.selected()); await type(harness, 'Delhi x'); assert.equal(harness.selected(), null); harness.close(); });
test('provider rejection renders an error without unhandled rejection and next input retries', async () => { let attempts = 0; const provider = { search: async () => { if (++attempts === 1) throw new Error('Provider unavailable'); return [{ city: 'Delhi', state: 'Delhi', country: 'India', latitude: 28.6139, longitude: 77.209, placeId: 'delhi' }]; } }; const harness = createHarness({ provider }); await type(harness, 'Del'); assert.match(harness.results.textContent, /Provider unavailable/); await type(harness, 'Deli'); assert.match(harness.results.textContent, /Delhi/); harness.close(); });
test('destroy cancels pending debounce and prevents stale rendering', async () => { let callback; let cleared = false; const states = []; const clock = { setTimeout(value) { callback = value; return 7; }, clearTimeout(id) { assert.equal(id, 7); cleared = true; } }; const controller = new LocationAutocompleteController({ provider: { search: async () => [{ city: 'Delhi' }] }, clock, onState: (state) => states.push(state.status) }); controller.input('Del'); controller.destroy(); assert.equal(cleared, true); await callback(); assert.deepEqual(states, ['loading']); });
test('destroying and reopening bindings does not duplicate input listeners', async () => { const fixture = domFixture(); let searches = 0; const makeBinding = () => { const controller = new LocationAutocompleteController({ provider: { search: async () => { searches++; return []; } }, debounceMs: 0, clock: createBrowserClock(fixture.dom.window) }); return new LocationAutocompleteDomBinding({ input: fixture.input, results: fixture.results, documentTarget: fixture.document, controller, onSelect: async () => {} }); }; const first = makeBinding(); first.destroy(); const second = makeBinding(); fixture.input.value = 'Del'; fixture.input.dispatchEvent(new fixture.dom.window.Event('input', { bubbles: true })); await wait(10); assert.equal(searches, 1); second.destroy(); fixture.dom.window.close(); });
