import test from 'node:test'; import assert from 'node:assert/strict'; import { IDBFactory } from 'fake-indexeddb';
import { IndexedDbAdapter, INDEXEDDB_PHYSICAL_VERSION, REQUIRED_STORE_NAMES, validateSchemaIntegrity } from '../src/data/indexeddb-adapter.js';
import { RoutineRepository } from '../src/data/routine-repository.js'; import { STORE_NAMES } from '../src/data/models.js';

function request(request) { return new Promise((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function createRawDatabase(indexedDB, name, version, { omit = [], metadataVersion = 2 } = {}) {
  const open = indexedDB.open(name, version); open.onupgradeneeded = () => { const db = open.result; const definitions = [[STORE_NAMES.metadata, 'key'], [STORE_NAMES.settings, 'id'], [STORE_NAMES.profiles, 'id'], [STORE_NAMES.activities, 'id'], [STORE_NAMES.dailyRoutines, 'date'], [STORE_NAMES.completions, 'id'], [STORE_NAMES.alarmStates, 'date'], [STORE_NAMES.fastingRanges, 'id'], [STORE_NAMES.prayerTimings, 'date']]; for (const [store, keyPath] of definitions) if (!omit.includes(store)) db.createObjectStore(store, { keyPath }); };
  const db = await request(open); if (db.objectStoreNames.contains(STORE_NAMES.metadata)) { const tx = db.transaction([STORE_NAMES.metadata], 'readwrite'); tx.objectStore(STORE_NAMES.metadata).put({ key: 'schemaVersion', value: metadataVersion }); await new Promise((resolve, reject) => { tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); }); } return db;
}

test('schema integrity reports every required store', async () => { const indexedDB = new IDBFactory(), adapter = new IndexedDbAdapter({ name: 'integrity', indexedDB }); const db = await adapter.open(); const integrity = validateSchemaIntegrity(db); assert.equal(integrity.valid, true); assert.deepEqual(integrity.existingStores.sort(), [...REQUIRED_STORE_NAMES].sort()); adapter.close(); });

test('physical version 1 upgrades and creates every schema 2 store', async () => { const indexedDB = new IDBFactory(); const old = await createRawDatabase(indexedDB, 'v1-upgrade', 1, { omit: [STORE_NAMES.profiles], metadataVersion: 1 }); old.onversionchange = () => old.close(); const repository = new RoutineRepository(new IndexedDbAdapter({ name: 'v1-upgrade', indexedDB })); const result = await repository.initialize(); assert.equal(result.schemaVersion, 2); assert.equal(result.diagnostics.physicalVersion, INDEXEDDB_PHYSICAL_VERSION); assert.equal(result.diagnostics.objectStores.includes(STORE_NAMES.profiles), true); repository.adapter.close(); });

test('metadata 2 with missing profiles is repaired without deleting records', async () => { const indexedDB = new IDBFactory(); const broken = await createRawDatabase(indexedDB, 'broken-v2', 2, { omit: [STORE_NAMES.profiles], metadataVersion: 2 }); const tx = broken.transaction([STORE_NAMES.activities, STORE_NAMES.completions], 'readwrite'); tx.objectStore(STORE_NAMES.activities).put({ id: 'keep-me', name: 'Keep Me', defaultTime: '8:00 AM', order: 3, enabled: true }); tx.objectStore(STORE_NAMES.completions).put({ id: '2026-01-01:keep-me', date: '2026-01-01', activityId: 'keep-me', completed: true }); await new Promise((resolve) => { tx.oncomplete = resolve; }); broken.onversionchange = () => broken.close(); const repository = new RoutineRepository(new IndexedDbAdapter({ name: 'broken-v2', indexedDB })); const result = await repository.initialize(); assert.equal(result.diagnostics.objectStores.includes('profiles'), true); assert.equal((await repository.getActivities()).some(({ id }) => id === 'keep-me'), true); assert.equal((await repository.adapter.get(STORE_NAMES.completions, '2026-01-01:keep-me')).completed, true); repository.adapter.close(); });

test('broken current physical version performs a safe repair upgrade', async () => { const indexedDB = new IDBFactory(); const broken = await createRawDatabase(indexedDB, 'repair-current', INDEXEDDB_PHYSICAL_VERSION, { omit: [STORE_NAMES.profiles] }); broken.close(); const adapter = new IndexedDbAdapter({ name: 'repair-current', indexedDB }); const db = await adapter.open(); assert.equal(db.version, INDEXEDDB_PHYSICAL_VERSION + 1); assert.equal(adapter.repairPerformed, true); assert.equal(validateSchemaIntegrity(db).valid, true); adapter.close(); });

test('concurrent repository initialization shares one open connection', async () => { const indexedDB = new IDBFactory(); let opens = 0; const original = indexedDB.open.bind(indexedDB); indexedDB.open = (...args) => { opens++; return original(...args); }; const repository = new RoutineRepository(new IndexedDbAdapter({ name: 'concurrent', indexedDB })); const first = repository.initialize(), second = repository.initialize(); assert.equal(first, second); await Promise.all([first, second]); assert.equal(opens, 1); repository.adapter.close(); });

test('stale closed connection reopens for the next transaction', async () => { const adapter = new IndexedDbAdapter({ name: 'stale', indexedDB: new IDBFactory() }); const first = await adapter.open(); first.close(); adapter.invalidateConnection(first); await adapter.put(STORE_NAMES.settings, { id: 'stale', ok: true }); assert.equal((await adapter.get(STORE_NAMES.settings, 'stale')).ok, true); adapter.close(); });

test('transaction retries once after InvalidStateError from a closing connection', async () => { const adapter = new IndexedDbAdapter({ name: 'closing', indexedDB: new IDBFactory() }); const first = await adapter.open(), original = first.transaction.bind(first); let calls = 0; first.transaction = (...args) => { if (calls++ === 0) throw new DOMException('Connection is closing.', 'InvalidStateError'); return original(...args); }; await adapter.put(STORE_NAMES.settings, { id: 'retry', ok: true }); assert.equal((await adapter.get(STORE_NAMES.settings, 'retry')).ok, true); first.close(); adapter.close(); });

test('cached old connection closes during an authoritative upgrade', async () => { const indexedDB = new IDBFactory(); const old = await createRawDatabase(indexedDB, 'blocked-upgrade', 2, { omit: [STORE_NAMES.profiles] }); let changed = false; old.onversionchange = () => { changed = true; old.close(); }; const adapter = new IndexedDbAdapter({ name: 'blocked-upgrade', indexedDB }); await adapter.open(); assert.equal(changed, true); assert.equal(validateSchemaIntegrity(adapter.db).valid, true); adapter.close(); });
