import test from 'node:test';
import assert from 'node:assert/strict';
import { IDBFactory } from 'fake-indexeddb';
import { IndexedDbAdapter } from '../src/data/indexeddb-adapter.js';
import { RoutineRepository } from '../src/data/routine-repository.js';
import { DevelopmentLocationProvider, GooglePlacesProvider, resolveTimezone } from '../src/location/providers.js';
import { LocationAutocompleteController } from '../src/location/autocomplete-controller.js';
import { DEFAULT_LOCATION_SUGGESTION, canActivateLocationDraft, createLocationProfile, validateCoordinates } from '../src/location/location-model.js';
import { calculatePrayerTimes, prayerSettingsFingerprint } from '../src/prayer/prayer-calculator.js';
import { PrayerCacheService } from '../src/prayer/prayer-cache.js';
import { STORE_NAMES } from '../src/data/models.js';

async function setup(name = `correction-${Math.random()}`) { const adapter = new IndexedDbAdapter({ name, indexedDB: new IDBFactory() }); const repository = new RoutineRepository(adapter); await repository.initialize(); return { adapter, repository }; }
const delhi = { ...DEFAULT_LOCATION_SUGGESTION, placeId: 'mock-delhi', city: 'Delhi', state: 'Delhi', latitude: 28.6139, longitude: 77.209, locationSource: 'development-mock' };
const mumbai = { ...DEFAULT_LOCATION_SUGGESTION, placeId: 'mock-mumbai', city: 'Mumbai', state: 'Maharashtra', latitude: 19.076, longitude: 72.8777, locationSource: 'development-mock' };

test('development search never turns arbitrary text into Ghaziabad and returns multiple cities', async () => { const provider = new DevelopmentLocationProvider(); assert.deepEqual(await provider.search('xyz'), []); const results = await provider.search('India'); assert.ok(results.length >= 7); assert.ok(results.some(({ city }) => city === 'Delhi')); assert.ok(results.some(({ city }) => city === 'Mumbai')); });
test('Delhi and Mumbai selection resolve their own coordinates and timezone', async () => { const provider = new DevelopmentLocationProvider(); const selectedDelhi = await provider.details((await provider.search('Del'))[0].placeId); const selectedMumbai = await provider.details((await provider.search('Mum'))[0].placeId); assert.deepEqual([selectedDelhi.city, selectedDelhi.latitude, selectedDelhi.timeZone], ['Delhi', 28.6139, 'Asia/Kolkata']); assert.deepEqual([selectedMumbai.city, selectedMumbai.longitude, selectedMumbai.timeZone], ['Mumbai', 72.8777, 'Asia/Kolkata']); });
test('Google Places uses live API only with key, session token, and minimal details fields', async () => { const calls = []; const fetchImpl = async (url, options = {}) => { calls.push({ url, options }); return url.includes('autocomplete') ? { ok: true, json: async () => ({ suggestions: [{ placePrediction: { placeId: 'delhi-id', text: { text: 'Delhi, India' }, structuredFormat: { mainText: { text: 'Delhi' }, secondaryText: { text: 'Delhi, India' } } } }] }) } : { ok: true, json: async () => ({ id: 'delhi-id', displayName: { text: 'Delhi' }, formattedAddress: 'Delhi, India', location: { latitude: 28.6139, longitude: 77.209 }, addressComponents: [{ longText: 'Delhi', types: ['locality'] }, { longText: 'Delhi', types: ['administrative_area_level_1'] }, { longText: 'India', types: ['country'] }] }) }; }; const provider = new GooglePlacesProvider({ apiKey: 'test-key-long-enough', fetchImpl }); const suggestions = await provider.search('Del'); const place = await provider.details(suggestions[0].placeId); assert.equal(place.city, 'Delhi'); assert.match(calls[0].options.body, /sessionToken/); assert.match(calls[1].options.headers['X-Goog-FieldMask'], /formattedAddress/); });
test('autocomplete is debounced', async () => { const timers = [], searched = []; const controller = new LocationAutocompleteController({ provider: { search: async (query) => { searched.push(query); return []; } }, debounceMs: 10, schedule: (callback) => { timers.push(callback); return timers.length; }, cancel: () => {} }); controller.input('De'); controller.input('Del'); await timers.at(-1)(); assert.deepEqual(searched, ['Del']); });
test('stale autocomplete results cannot replace newer results', async () => { const resolvers = {}; const states = []; const controller = new LocationAutocompleteController({ provider: { search: (query) => new Promise((resolve) => { resolvers[query] = resolve; }) }, debounceMs: 0, onState: (state) => states.push(structuredClone(state)) }); const first = controller.run('De', 1); controller.requestId = 2; const second = controller.run('Del', 2); resolvers.Del([{ city: 'Delhi' }]); await second; resolvers.De([{ city: 'Old' }]); await first; assert.equal(controller.state.results[0].city, 'Delhi'); });
test('typing without selection cannot activate profile and text changes clear identity policy', () => { assert.equal(canActivateLocationDraft({ selectedPlace: null, coordinatesChanged: false }), false); assert.equal(canActivateLocationDraft({ selectedPlace: delhi, coordinatesChanged: false }), true); assert.equal(canActivateLocationDraft({ selectedPlace: null, coordinatesChanged: true }), true); });
test('invalid manual coordinates are rejected and valid changes resolve timezone', () => { assert.throws(() => validateCoordinates(91, 77), /Latitude/); assert.throws(() => validateCoordinates(28, -181), /Longitude/); const values = validateCoordinates(51.5074, -0.1278); assert.equal(resolveTimezone(values.latitude, values.longitude), 'Europe/London'); });
test('location version and prayer fingerprint change for coordinate, method and madhab changes', () => { const base = createLocationProfile({ ...delhi, locationVersion: '1' }); const coordinate = createLocationProfile({ ...mumbai, locationVersion: '2' }); const method = createLocationProfile({ ...delhi, calculationMethod: 'MuslimWorldLeague', locationVersion: '2' }); const madhab = createLocationProfile({ ...delhi, madhab: 'Shafi', locationVersion: '2' }); assert.equal(new Set([base, coordinate, method, madhab].map(prayerSettingsFingerprint)).size, 4); });
test('materially different coordinates produce different prayer timings', () => { const date = '2026-08-02'; const a = calculatePrayerTimes(date, createLocationProfile(delhi)); const b = calculatePrayerTimes(date, createLocationProfile(mumbai)); assert.notDeepEqual([a.fajr, a.dhuhr, a.maghrib], [b.fajr, b.dhuhr, b.maghrib]); });
test('fingerprint change regenerates current and next month and remains offline-cacheable', async () => { const { adapter } = await setup(); const cache = new PrayerCacheService(adapter); const firstProfile = createLocationProfile({ ...delhi, locationVersion: '1' }); await cache.warmCurrentAndNext('2026-08-02', firstProfile); const secondProfile = createLocationProfile({ ...mumbai, locationVersion: '2' }); const records = await cache.warmCurrentAndNext('2026-08-02', secondProfile); assert.equal(records.length, 61); assert.ok(records.every(({ settingsFingerprint }) => settingsFingerprint === prayerSettingsFingerprint(secondProfile))); cache.calculator = () => { throw new Error('must use offline cache'); }; assert.equal((await cache.get('2026-09-15', secondProfile)).settingsFingerprint, prayerSettingsFingerprint(secondProfile)); adapter.close(); });
test('confirmed location increments version and old fingerprint is not reused', async () => { const { repository, adapter } = await setup(); const first = await repository.saveLocationProfile(delhi, { currentDate: '2026-08-02' }); const before = await repository.prayerCache.get('2026-08-02', first); const second = await repository.saveLocationProfile(mumbai, { currentDate: '2026-08-02' }); const after = await repository.prayerCache.get('2026-08-02', second); assert.equal(Number(second.locationVersion), Number(first.locationVersion) + 1); assert.notEqual(after.settingsFingerprint, before.settingsFingerprint); adapter.close(); });
test('historical snapshots remain unchanged after a location change', async () => { const { repository, adapter } = await setup(); await repository.saveLocationProfile(delhi, { currentDate: '2026-08-01' }); const old = await repository.getDay('2026-08-01'); await repository.saveLocationProfile(mumbai, { currentDate: '2026-08-02' }); assert.deepEqual((await repository.getDay('2026-08-01')).occurrences, old.occurrences); adapter.close(); });
test('future uncompleted prayer snapshots refresh after location change', async () => { const { repository, adapter } = await setup(); await repository.saveLocationProfile(delhi, { currentDate: '2026-08-02' }); const before = await repository.getDay('2026-09-10'); const fajrBefore = before.occurrences.find(({ activityId }) => activityId === 'fajr').time; await repository.saveLocationProfile(mumbai, { currentDate: '2026-08-02' }); const after = await repository.getDay('2026-09-10'); assert.notEqual(after.occurrences.find(({ activityId }) => activityId === 'fajr').time, fajrBefore); assert.notEqual(after.prayerTimes.settingsFingerprint, before.prayerTimes.settingsFingerprint); adapter.close(); });
test('completed prayer occurrence identity, timing and completion survive refresh', async () => { const { repository, adapter } = await setup(); await repository.saveLocationProfile(delhi, { currentDate: '2026-08-02' }); const before = await repository.getDay('2026-08-02'); const fajr = before.occurrences.find(({ activityId }) => activityId === 'fajr'); await repository.setCompletion(before.date, fajr.id, true); await repository.saveLocationProfile(mumbai, { currentDate: '2026-08-02' }); const after = await repository.getDay('2026-08-02'); const preserved = after.occurrences.find(({ id }) => id === fajr.id); assert.equal(preserved.time, fajr.time); assert.equal(after.completions[fajr.id], true); adapter.close(); });
test('protected prayer activities reject name, time, schedule and deletion but allow enable and notification', async () => { const { repository, adapter } = await setup(); const fajr = (await repository.getActivities()).find(({ id }) => id === 'fajr'); await assert.rejects(repository.editActivity('fajr', { name: 'Custom' }), /Protected prayer/); await assert.rejects(repository.editActivity('fajr', { defaultTime: '9:00 AM' }), /Protected prayer/); await assert.rejects(repository.editActivity('fajr', { schedule: { type: 'none' } }), /Protected prayer/); await assert.rejects(repository.editActivity('fajr', { timeSlots: [{ ...fajr.timeSlots[0], time: '9:00 AM' }] }), /Protected prayer/); await assert.rejects(repository.softDeleteActivity('fajr'), /Protected prayer/); assert.equal((await repository.editActivity('fajr', { enabled: false })).enabled, false); const toggled = await repository.editActivity('fajr', { timeSlots: fajr.timeSlots.map((slot) => ({ ...slot, notificationEnabled: !slot.notificationEnabled })) }); assert.equal(toggled.timeSlots[0].notificationEnabled, !fajr.timeSlots[0].notificationEnabled); adapter.close(); });
test('Sehri is derived from Fajr and appears only on fasting dates', async () => { const { repository, adapter } = await setup(); await repository.saveLocationProfile({ ...delhi, sehriOffsetMinutes: 45 }, { currentDate: '2026-08-02' }); const friday = await repository.getDay('2026-08-07'); const saturday = await repository.getDay('2026-08-08'); const sehri = friday.occurrences.find(({ activityId }) => activityId === 'sehri'); assert.ok(sehri); assert.equal(sehri.time, friday.prayerTimes.sehri); assert.equal(saturday.occurrences.some(({ activityId }) => activityId === 'sehri'), false); adapter.close(); });
test('normal activities remain fully editable', async () => { const { repository, adapter } = await setup(); const edited = await repository.editActivity('gym', { name: 'Strength', schedule: { type: 'selected-weekdays', weekdays: ['Monday'] }, timeSlots: [{ id: 'gym-time-1', time: '6:00 PM', notificationEnabled: true }] }); assert.equal(edited.name, 'Strength'); assert.equal(edited.timeSlots[0].time, '6:00 PM'); adapter.close(); });
test('profile save failure keeps previously active profile', async () => { const indexedDB = new IDBFactory(); const adapter = new IndexedDbAdapter({ name: 'rollback-profile', indexedDB }); const cache = new PrayerCacheService(adapter); const repository = new RoutineRepository(adapter, { prayerCache: cache }); await repository.initialize(); const original = await repository.saveLocationProfile(delhi, { currentDate: '2026-08-02' }); cache.warmCurrentAndNext = async () => { throw new Error('cache failed'); }; await assert.rejects(repository.saveLocationProfile(mumbai, { currentDate: '2026-08-02' }), /cache failed/); assert.equal((await repository.getLocationProfile()).city, original.city); adapter.close(); });
test('migrated database reconciles canonical protection without deleting history', async () => { const { repository, adapter } = await setup(); const routine = await repository.getDay('2026-08-02'); const count = (await adapter.getAll(STORE_NAMES.dailyRoutines)).length; await repository.reconcileProtectedActivities(); assert.equal((await repository.getActivities()).find(({ id }) => id === 'fajr').protected, true); assert.equal((await adapter.getAll(STORE_NAMES.dailyRoutines)).length, count); assert.equal((await repository.getDay(routine.date)).date, routine.date); adapter.close(); });
