import test from 'node:test'; import assert from 'node:assert/strict'; import { IDBFactory } from 'fake-indexeddb';
import { IndexedDbAdapter } from '../src/data/indexeddb-adapter.js'; import { RoutineRepository } from '../src/data/routine-repository.js'; import { STORE_NAMES } from '../src/data/models.js';
import { DEFAULT_LOCATION_SUGGESTION, createLocationProfile } from '../src/location/location-model.js'; import { LocationSetupService } from '../src/location/location-service.js';
import { resolveTimezone } from '../src/location/providers.js';
import { calculatePrayerTimes, prayerSettingsFingerprint } from '../src/prayer/prayer-calculator.js'; import { PrayerCacheService } from '../src/prayer/prayer-cache.js';

async function setup(name = `prayer-${Math.random()}`) { const adapter = new IndexedDbAdapter({ name, indexedDB: new IDBFactory() }); const repository = new RoutineRepository(adapter); await repository.initialize(); return { adapter, repository }; }

test('first run has no saved profile and Ghaziabad is the default suggestion', async () => { const { repository, adapter } = await setup(); assert.equal(await repository.getLocationProfile(), undefined); const service = new LocationSetupService({ geolocation: {}, reverseGeocoder: {}, searchProvider: {} }); assert.equal(service.getDefaultSuggestion().city, 'Ghaziabad'); adapter.close(); });

test('location permission denial returns manual-search fallback', async () => { const service = new LocationSetupService({ geolocation: { detect: async () => { throw new Error('Permission denied'); } }, reverseGeocoder: {}, searchProvider: { search: async () => [] } }); const result = await service.detectOrFallback(); assert.equal(result.detected, false); assert.equal(result.location.city, 'Ghaziabad'); assert.match(result.error, /Permission denied/); });

test('mock detection and reverse geocoding create foreground result', async () => { const service = new LocationSetupService({ geolocation: { detect: async () => ({ latitude: 19.076, longitude: 72.8777 }) }, reverseGeocoder: { reverseGeocode: async () => ({ city: 'Mumbai', state: 'Maharashtra', country: 'India', timeZone: 'Asia/Kolkata' }) }, searchProvider: {} }); const result = await service.detect(); assert.equal(result.city, 'Mumbai'); assert.equal(result.locationSource, 'device-foreground'); });
test('coordinates resolve to an IANA timezone offline', () => { assert.equal(resolveTimezone(28.6692, 77.4538), 'Asia/Kolkata'); assert.equal(resolveTimezone(51.5074, -0.1278), 'Europe/London'); });

test('first-run location profile creation stores every required field', async () => { const { repository, adapter } = await setup(); const saved = await repository.saveLocationProfile(DEFAULT_LOCATION_SUGGESTION, { currentDate: '2026-08-02' }); assert.equal(saved.city, 'Ghaziabad'); assert.equal(saved.timeZone, 'Asia/Kolkata'); assert.equal(saved.calculationMethod, 'Karachi'); assert.equal(saved.madhab, 'Hanafi'); assert.ok(saved.locationSource); assert.ok(saved.updatedAt); adapter.close(); });

test('local prayer calculation for known Ghaziabad date returns six ordered prayers', () => { const profile = createLocationProfile(DEFAULT_LOCATION_SUGGESTION); const times = calculatePrayerTimes('2026-08-02', profile); assert.equal(times.source, 'adhan-local'); assert.deepEqual([times.fajr, times.sunrise, times.dhuhr, times.asr, times.maghrib, times.isha], ['4:14 AM', '5:42 AM', '12:27 PM', '5:11 PM', '7:11 PM', '8:38 PM']); });

test('prayer cache generates current and next month', async () => { const { adapter } = await setup(); const cache = new PrayerCacheService(adapter); const records = await cache.warmCurrentAndNext('2026-08-02', createLocationProfile(DEFAULT_LOCATION_SUGGESTION)); assert.equal(records.length, 61); assert.equal((await adapter.getAll(STORE_NAMES.prayerTimings)).length, 61); adapter.close(); });

test('cached prayer record is reused without calculator access', async () => { const { adapter } = await setup(); const profile = createLocationProfile(DEFAULT_LOCATION_SUGGESTION), cache = new PrayerCacheService(adapter); const first = await cache.get('2026-08-02', profile); cache.calculator = () => { throw new Error('offline calculator should not run'); }; assert.deepEqual(await cache.get('2026-08-02', profile), first); adapter.close(); });

test('location, method and madhab changes produce distinct cache fingerprints', () => { const base = createLocationProfile({ ...DEFAULT_LOCATION_SUGGESTION, locationVersion: '1' }); const moved = createLocationProfile({ ...DEFAULT_LOCATION_SUGGESTION, latitude: 28.7, locationVersion: '2' }); const method = createLocationProfile({ ...DEFAULT_LOCATION_SUGGESTION, calculationMethod: 'MuslimWorldLeague', locationVersion: '1' }); const madhab = createLocationProfile({ ...DEFAULT_LOCATION_SUGGESTION, madhab: 'Shafi', locationVersion: '1' }); assert.equal(new Set([base, moved, method, madhab].map(prayerSettingsFingerprint)).size, 4); });

test('cache invalidates and regenerates after method or madhab changes', async () => { const { adapter } = await setup(); const cache = new PrayerCacheService(adapter), base = createLocationProfile({ ...DEFAULT_LOCATION_SUGGESTION, locationVersion: '1' }); const first = await cache.get('2026-08-02', base); const method = await cache.get('2026-08-02', createLocationProfile({ ...DEFAULT_LOCATION_SUGGESTION, calculationMethod: 'MuslimWorldLeague', locationVersion: '2' })); const madhab = await cache.get('2026-08-02', createLocationProfile({ ...DEFAULT_LOCATION_SUGGESTION, madhab: 'Shafi', locationVersion: '3' })); assert.notEqual(first.settingsFingerprint, method.settingsFingerprint); assert.notEqual(method.settingsFingerprint, madhab.settingsFingerprint); assert.equal((await adapter.get(STORE_NAMES.prayerTimings, '2026-08-02')).settingsFingerprint, madhab.settingsFingerprint); adapter.close(); });

test('location change invalidates future cache but preserves historical daily snapshot', async () => { const { repository, adapter } = await setup(); await repository.saveLocationProfile(DEFAULT_LOCATION_SUGGESTION, { currentDate: '2026-08-01' }); const historical = await repository.getDay('2026-08-02'), oldTimes = structuredClone(historical.prayerTimes), oldOccurrences = structuredClone(historical.occurrences); await repository.saveLocationProfile({ ...DEFAULT_LOCATION_SUGGESTION, city: 'Delhi', state: 'Delhi', latitude: 28.6139, longitude: 77.209, locationSource: 'manual' }, { currentDate: '2026-08-03' }); const preserved = await repository.getDay('2026-08-02'), future = await repository.getDay('2026-10-01'); assert.deepEqual(preserved.occurrences, oldOccurrences); assert.deepEqual(preserved.prayerTimes, oldTimes); assert.notEqual(future.prayerTimes.settingsFingerprint, oldTimes.settingsFingerprint); adapter.close(); });
