import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { IDBFactory } from 'fake-indexeddb';
import { CalculationMethod, Coordinates, HighLatitudeRule, PrayerTimes } from 'adhan';
import { IndexedDbAdapter } from '../src/data/indexeddb-adapter.js';
import { RoutineRepository } from '../src/data/routine-repository.js';
import { STORE_NAMES } from '../src/data/models.js';
import { createLocationProfile } from '../src/location/location-model.js';
import { PrayerCacheService } from '../src/prayer/prayer-cache.js';
import { PRAYER_CACHE_FORMAT_VERSION, calculatePrayerTimes, calculationParametersForProfile, createAdhanCalendarDate, formatPrayerInstant, inspectPrayerCalculation, prayerSettingsFingerprint, resolveHighLatitudeRule } from '../src/prayer/prayer-calculator.js';
import { homePrayerDisplayValues } from '../src/ui/prayer-display.js';

const londonSummer = createLocationProfile({ city: 'London', state: 'England', country: 'United Kingdom', latitude: 51.5074, longitude: -0.1278, timeZone: 'Europe/London', calculationMethod: 'MoonsightingCommittee', madhab: 'Hanafi', highLatitudeRule: 'recommended', polarCircleResolution: 'Unresolved', shafaq: 'general', adjustments: { fajr: 3 }, sehriOffsetMinutes: 30, locationVersion: 'accuracy-1' });
const londonWinter = createLocationProfile({ ...londonSummer, adjustments: { fajr: 0 }, locationVersion: 'accuracy-2' });
const cityFixtures = [
  ['Ghaziabad Karachi recommended', 28.6692, 77.4538, 'Asia/Kolkata', 'Karachi'], ['Delhi Muslim World League recommended', 28.6139, 77.209, 'Asia/Kolkata', 'MuslimWorldLeague'], ['Mumbai Karachi recommended', 19.076, 72.8777, 'Asia/Kolkata', 'Karachi'], ['London winter Moonsighting recommended', 51.5074, -0.1278, 'Europe/London', 'MoonsightingCommittee'], ['London summer Moonsighting recommended', 51.5074, -0.1278, 'Europe/London', 'MoonsightingCommittee'], ['Dubai Dubai-method recommended', 25.2048, 55.2708, 'Asia/Dubai', 'Dubai'],
];
async function setup(name = `accuracy-${Math.random()}`) { const adapter = new IndexedDbAdapter({ name, indexedDB: new IDBFactory() }); const repository = new RoutineRepository(adapter); await repository.initialize(); return { adapter, repository }; }

test('London 2026-08-02 Moonsighting Committee, recommended rule, +3 Fajr adjustment agrees across direct Adhan, cache, snapshot and Home', async () => {
  const coordinates = new Coordinates(51.5074, -0.1278), parameters = CalculationMethod.MoonsightingCommittee(); parameters.highLatitudeRule = HighLatitudeRule.recommended(coordinates); parameters.adjustments.fajr = 3;
  const direct = new PrayerTimes(coordinates, createAdhanCalendarDate('2026-08-02'), parameters); const directLocal = formatPrayerInstant(direct.fajr, 'Europe/London'); const calculated = calculatePrayerTimes('2026-08-02', londonSummer);
  assert.equal(direct.fajr.toISOString(), '2026-08-02T02:41:00.000Z'); assert.equal(directLocal, '3:41 AM'); assert.equal(calculated.rawInstants.fajr, direct.fajr.toISOString()); assert.equal(calculated.fajr, directLocal); assert.equal(calculated.timezoneOffset, 'GMT+01:00');
  const { adapter, repository } = await setup(); await repository.saveLocationProfile(londonSummer, { currentDate: '2026-08-02' }); const cached = await adapter.get(STORE_NAMES.prayerTimings, '2026-08-02'), day = await repository.getDay('2026-08-02'); assert.equal(cached.fajr, directLocal); assert.equal(day.prayerTimes.fajr, directLocal); assert.equal(day.occurrences.find(({ activityId }) => activityId === 'fajr').time, directLocal); assert.equal(homePrayerDisplayValues(day).fajr, directLocal); adapter.close();
});

test('London observes BST in summer and GMT in winter', () => { const summer = calculatePrayerTimes('2026-08-02', londonSummer), winter = calculatePrayerTimes('2026-01-02', londonWinter); assert.equal(summer.timezoneOffset, 'GMT+01:00'); assert.equal(winter.timezoneOffset, 'GMT+00:00'); assert.equal(formatPrayerInstant(new Date(summer.rawInstants.fajr), 'Europe/London'), summer.fajr); assert.equal(formatPrayerInstant(new Date(winter.rawInstants.fajr), 'Europe/London'), winter.fajr); });
test('London Fajr is not displayed as its UTC clock value during BST', () => { const value = calculatePrayerTimes('2026-08-02', londonSummer); assert.equal(value.rawInstants.fajr.slice(11, 16), '02:41'); assert.equal(value.fajr, '3:41 AM'); });
test('requested Gregorian components survive GMT, BST, India, DST boundaries and year boundaries', () => { for (const date of ['2026-01-01', '2026-03-28', '2026-03-29', '2026-10-25', '2026-10-26', '2026-12-31']) { const target = createAdhanCalendarDate(date); assert.equal(`${target.getFullYear()}-${String(target.getMonth() + 1).padStart(2, '0')}-${String(target.getDate()).padStart(2, '0')}`, date); } });
test('London profile result is independent of process/device timezone', () => { const moduleUrl = new URL('../src/prayer/prayer-calculator.js', import.meta.url).href, profile = JSON.stringify(londonSummer); const code = `import {calculatePrayerTimes} from ${JSON.stringify(moduleUrl)}; console.log(JSON.stringify(calculatePrayerTimes('2026-08-02', ${profile})))`; const values = ['UTC', 'Asia/Kolkata', 'America/New_York'].map((TZ) => JSON.parse(execFileSync(process.execPath, ['--input-type=module', '-e', code], { env: { ...process.env, TZ }, encoding: 'utf8' }))); assert.equal(new Set(values.map(({ fajr }) => fajr)).size, 1); assert.equal(new Set(values.map(({ rawInstants }) => rawInstants.fajr)).size, 1); });
test('recommended and explicit high-latitude rules resolve and fingerprint distinctly', () => { const coordinates = new Coordinates(51.5074, -0.1278); assert.equal(resolveHighLatitudeRule('recommended', coordinates), HighLatitudeRule.SeventhOfTheNight); assert.equal(resolveHighLatitudeRule('middleOfTheNight', coordinates), HighLatitudeRule.MiddleOfTheNight); assert.equal(resolveHighLatitudeRule('twilightAngle', coordinates), HighLatitudeRule.TwilightAngle); const fingerprints = ['recommended', 'middleOfTheNight', 'seventhOfTheNight', 'twilightAngle', 'none'].map((highLatitudeRule) => prayerSettingsFingerprint({ ...londonSummer, highLatitudeRule })); assert.equal(new Set(fingerprints).size, 5); });
test('timezone, angle, polar resolution and shafaq settings change fingerprints', () => { const variants = [londonSummer, { ...londonSummer, timeZone: 'UTC' }, { ...londonSummer, fajrAngleOverride: 17 }, { ...londonSummer, ishaAngleOverride: 16 }, { ...londonSummer, polarCircleResolution: 'AqrabYaum' }, { ...londonSummer, shafaq: 'abyad' }]; assert.equal(new Set(variants.map(prayerSettingsFingerprint)).size, variants.length); });
test('visible method mapping selects intended Adhan parameters and unknown methods fail', () => { const expected = { MuslimWorldLeague: [18, 17, 0], Egyptian: [19.5, 17.5, 0], Karachi: [18, 18, 0], UmmAlQura: [18.5, 0, 90], Dubai: [18.2, 18.2, 0], Qatar: [18, 0, 90], Kuwait: [18, 17.5, 0], MoonsightingCommittee: [18, 18, 0], Singapore: [20, 18, 0], Turkey: [18, 17, 0], Tehran: [17.7, 14, 0], NorthAmerica: [15, 15, 0] }; for (const [calculationMethod, values] of Object.entries(expected)) { const { parameters } = calculationParametersForProfile({ ...londonSummer, calculationMethod }); assert.deepEqual([parameters.fajrAngle, parameters.ishaAngle, parameters.ishaInterval], values); } assert.throws(() => calculationParametersForProfile({ ...londonSummer, calculationMethod: 'Unknown' }), /Unknown prayer calculation method/); });
test('manual Fajr adjustment is applied exactly once and Madhab does not change Fajr', () => { const base = calculatePrayerTimes('2026-08-02', { ...londonSummer, adjustments: { fajr: 0 } }), adjusted = calculatePrayerTimes('2026-08-02', { ...londonSummer, adjustments: { fajr: 5 } }), shafi = calculatePrayerTimes('2026-08-02', { ...londonSummer, adjustments: { fajr: 0 }, madhab: 'Shafi' }); assert.equal(new Date(adjusted.rawInstants.fajr) - new Date(base.rawInstants.fajr), 300000); assert.equal(shafi.rawInstants.fajr, base.rawInstants.fajr); });
test('Sehri offset is applied to the corrected Fajr instant in profile timezone', () => { const value = calculatePrayerTimes('2026-08-02', { ...londonSummer, adjustments: { fajr: 3 }, sehriOffsetMinutes: 30 }); assert.equal(value.fajr, '3:41 AM'); assert.equal(value.sehriStart, '3:11 AM'); assert.equal(value.sehri, '3:11 AM - 3:41 AM'); });
test('inspector exposes UTC, local, method and fingerprint values without changing data', () => { const result = inspectPrayerCalculation('2026-08-02', londonSummer); assert.equal(result.rawUtc.fajr, '2026-08-02T02:41:00.000Z'); assert.equal(result.local.fajr, '3:41 AM'); assert.equal(result.method.fajrAngle, 18); assert.equal(result.method.resolvedHighLatitudeRule, HighLatitudeRule.SeventhOfTheNight); assert.equal(result.timezoneOffset, 'GMT+01:00'); });
test('cache format 2 invalidates erroneous future cache while retaining historical cache and completion data', async () => { const { adapter, repository } = await setup(); await repository.saveLocationProfile(londonSummer, { currentDate: '2026-08-02' }); const past = await repository.getDay('2026-07-31'), occurrence = past.occurrences.find(({ activityId }) => activityId === 'fajr'); await repository.setCompletion(past.date, occurrence.id, true); await adapter.put(STORE_NAMES.prayerTimings, { date: '2026-07-31', fajr: 'OLD PAST', cacheFormatVersion: 1 }); await adapter.put(STORE_NAMES.prayerTimings, { date: '2026-10-01', fajr: 'OLD FUTURE', cacheFormatVersion: 1 }); await adapter.delete(STORE_NAMES.metadata, 'prayerCalculatorVersion'); const result = await repository.ensurePrayerCalculatorCurrent('2026-08-02'); assert.equal(result.upgraded, true); assert.equal((await adapter.get(STORE_NAMES.prayerTimings, '2026-07-31')).fajr, 'OLD PAST'); assert.equal((await adapter.get(STORE_NAMES.prayerTimings, '2026-10-01')), undefined); assert.equal((await repository.getDay('2026-07-31')).completions[occurrence.id], true); adapter.close(); });
for (const [name, latitude, longitude, timeZone, calculationMethod] of cityFixtures) test(`${name} fixture returns raw UTC and timezone-local values`, () => { const date = name.includes('winter') ? '2026-01-02' : '2026-08-02'; const profile = createLocationProfile({ city: name, country: 'Fixture', latitude, longitude, timeZone, calculationMethod, madhab: 'Hanafi', highLatitudeRule: 'recommended', polarCircleResolution: 'Unresolved', shafaq: 'general', adjustments: {}, locationVersion: 'fixture' }); const result = calculatePrayerTimes(date, profile); assert.match(result.rawInstants.fajr, /^2026-/); assert.equal(formatPrayerInstant(new Date(result.rawInstants.fajr), timeZone), result.fajr); assert.equal(result.cacheFormatVersion, PRAYER_CACHE_FORMAT_VERSION); });
