import test from 'node:test';
import assert from 'node:assert/strict';
import { IDBFactory } from 'fake-indexeddb';
import { IndexedDbAdapter } from '../src/data/indexeddb-adapter.js';
import { RoutineRepository } from '../src/data/routine-repository.js';
import { DEFAULT_ACTIVITIES } from '../src/data/defaults.js';
import { SCHEMA_VERSION, STORE_NAMES, createCompletionRecord } from '../src/data/models.js';
import { calculateActivityProgress, calculateMonthlyProgress } from '../src/data/progress.js';

async function setup(name = `test-${Math.random()}`) { const indexedDB = new IDBFactory(); const adapter = new IndexedDbAdapter({ name, indexedDB }); const repository = new RoutineRepository(adapter); const result = await repository.initialize(); return { indexedDB, adapter, repository, result }; }

test('database initializes schema 2 and seeds defaults once', async () => { const { adapter, repository, result } = await setup(); assert.equal(result.schemaVersion, SCHEMA_VERSION); assert.equal((await repository.getActivities()).length, 13); await repository.initialize(); assert.equal((await repository.getActivities()).length, 13); assert.ok([...adapter.db.objectStoreNames].includes('profiles')); adapter.close(); });

test('daily records contain applicable occurrence snapshots', async () => { const { repository, adapter } = await setup(); const day = await repository.getDay('2026-08-03'); assert.equal(day.weekday, 'Monday'); assert.ok(day.occurrences.every(({ id, timeSlotId }) => id && timeSlotId)); assert.equal((await repository.getMonth('2026-08')).length, 1); adapter.close(); });

test('multiple time slots complete and persist independently', async () => { const { indexedDB, adapter, repository } = await setup('occurrences'); await repository.addActivity({ id: 'medicine', name: 'Medicine', schedule: { type: 'daily' }, timeSlots: [{ id: 'morning', time: '8:00 AM' }, { id: 'evening', time: '9:00 PM' }] }); const day = await repository.getDay('2026-08-03'); const medicine = day.occurrences.filter(({ activityId }) => activityId === 'medicine'); assert.equal(medicine.length, 2); await repository.setCompletion(day.date, medicine[0].id, true); adapter.close(); const reopened = new RoutineRepository(new IndexedDbAdapter({ name: 'occurrences', indexedDB })); await reopened.initialize(); const persisted = await reopened.getDay(day.date); assert.equal(persisted.completions[medicine[0].id], true); assert.equal(persisted.completions[medicine[1].id], false); reopened.adapter.close(); });

test('time slots retain independent notification settings', async () => { const { repository, adapter } = await setup(); await repository.addActivity({ id: 'medicine', name: 'Medicine', timeSlots: [{ id: 'a', time: '8:00 AM', notificationEnabled: true, notificationOffsetMinutes: -10 }, { id: 'b', time: '2:00 PM', notificationEnabled: false }] }); const occurrences = (await repository.getDay('2026-08-04')).occurrences.filter(({ activityId }) => activityId === 'medicine'); assert.deepEqual(occurrences.map(({ notificationEnabled, notificationOffsetMinutes }) => [notificationEnabled, notificationOffsetMinutes]), [[true, -10], [false, 0]]); adapter.close(); });

test('activity schedule edits only affect future snapshots', async () => { const { repository, adapter } = await setup(); await repository.addActivity({ id: 'gym2', name: 'Gym 2', schedule: { type: 'daily' }, timeSlots: [{ id: 'one', time: '7:00 AM' }] }); const old = await repository.getDay('2026-08-03'); await repository.editActivity('gym2', { schedule: { type: 'monthly', dayOfMonth: 5 }, timeSlots: [{ id: 'two', time: '8:00 AM' }] }); const future = await repository.getDay('2026-08-04'); assert.ok(old.occurrences.some(({ timeSlotId }) => timeSlotId === 'one')); assert.equal(future.occurrences.some(({ activityId }) => activityId === 'gym2'), false); assert.ok((await repository.getDay('2026-08-05')).occurrences.some(({ timeSlotId }) => timeSlotId === 'two')); adapter.close(); });

test('soft deletion preserves historical occurrence completion', async () => { const { repository, adapter } = await setup(); await repository.addActivity({ id: 'journal', name: 'Journal', timeSlots: [{ id: 'night', time: '9:00 PM' }] }); const old = await repository.getDay('2026-08-03'); const occurrence = old.occurrences.find(({ activityId }) => activityId === 'journal'); await repository.setCompletion(old.date, occurrence.id, true); await repository.softDeleteActivity('journal'); assert.equal((await repository.getDay(old.date)).completions[occurrence.id], true); assert.equal((await repository.getDay('2026-08-04')).occurrences.some(({ activityId }) => activityId === 'journal'), false); adapter.close(); });

test('protected prayer mappings cannot be removed through activity edits', async () => { const { repository, adapter } = await setup(); await assert.rejects(() => repository.softDeleteActivity('fajr'), /Protected prayer/); await repository.editActivity('fajr', { timeSlots: [] }); const fajr = (await repository.getActivities()).find(({ id }) => id === 'fajr'); assert.equal(fajr.timeSlots[0].prayerKey, 'fajrPrayer'); adapter.close(); });

test('daily, monthly and yearly progress count occurrences', async () => { const { repository, adapter } = await setup(); await repository.addActivity({ id: 'medicine', name: 'Medicine', timeSlots: [{ id: 'a', time: '8:00 AM' }, { id: 'b', time: '8:00 PM' }] }); const first = await repository.getDay('2026-01-01'), second = await repository.getDay('2026-02-01'); const occurrence = first.occurrences.find(({ activityId }) => activityId === 'medicine'); await repository.setCompletion(first.date, occurrence.id, true); const month = calculateMonthlyProgress(await repository.getMonth('2026-01')); const year = calculateActivityProgress(await repository.getYear('2026'), 'medicine'); assert.equal(month.possible, first.occurrences.length); assert.deepEqual(year, { completed: 1, possible: 4, percent: 25 }); adapter.close(); });

test('alarm state persists for occurrence notification IDs', async () => { const { indexedDB, adapter, repository } = await setup('alarm-v2'); const day = await repository.getDay('2026-08-03'); const occurrence = day.occurrences.find(({ notificationEnabled }) => notificationEnabled); await repository.setAlarm(day.date, occurrence.notificationId, false); adapter.close(); const reopened = new RoutineRepository(new IndexedDbAdapter({ name: 'alarm-v2', indexedDB })); await reopened.initialize(); assert.ok((await reopened.getDay(day.date)).disabledAlarmIds.includes(occurrence.notificationId)); reopened.adapter.close(); });

test('schema 1 activity, snapshots, completions, alarms, ordering and deletion migrate without loss', async () => { const indexedDB = new IDBFactory(), adapter = new IndexedDbAdapter({ name: 'legacy', indexedDB }); await adapter.open(); await adapter.put(STORE_NAMES.metadata, { key: 'schemaVersion', value: 1 }); const legacy = { id: 'legacy', name: 'Legacy', defaultTime: '8:00 AM', enabled: true, order: 7, deletedAt: null, prayerKey: null, alarmId: null }; await adapter.put(STORE_NAMES.activities, legacy); await adapter.put(STORE_NAMES.dailyRoutines, { date: '2026-07-01', weekday: 'Wednesday', activitySnapshots: [legacy], createdAt: 'old' }); await adapter.put(STORE_NAMES.completions, createCompletionRecord('2026-07-01', 'legacy', true)); await adapter.put(STORE_NAMES.alarmStates, { date: '2026-07-01', enabled: false, disabledAlarmIds: ['OLD'] }); await adapter.put(STORE_NAMES.prayerTimings, { date: '2026-07-01', fajr: '4:00 AM', source: 'legacy' }); adapter.close(); const repository = new RoutineRepository(new IndexedDbAdapter({ name: 'legacy', indexedDB })); const result = await repository.initialize(); const activity = (await repository.getActivities()).find(({ id }) => id === 'legacy'), day = await repository.getDay('2026-07-01'); assert.equal(result.migratedFrom, 1); assert.equal(activity.order, 7); assert.equal(activity.schedule.type, 'daily'); assert.equal(activity.timeSlots[0].time, '8:00 AM'); assert.equal(day.completions['legacy:legacy-time-1'], true); assert.deepEqual(day.disabledAlarmIds, ['OLD']); assert.equal(day.prayerTimes.source, 'legacy'); repository.adapter.close(); });
