import test from 'node:test'; import assert from 'node:assert/strict'; import { IDBFactory } from 'fake-indexeddb';
import { IndexedDbAdapter } from '../src/data/indexeddb-adapter.js'; import { RoutineRepository } from '../src/data/routine-repository.js';
import { automaticCalculationMethod, automaticPrayerSettings, resetPrayerAdjustments } from '../src/prayer/automatic-settings.js';
import { createLocationProfile, validateDisplayName } from '../src/location/location-model.js'; import { mapLocationProfile, DevelopmentMapProvider } from '../src/location/map-provider.js'; import { DevelopmentLocationProvider } from '../src/location/providers.js';
import { profileHeading, profileLocationLabel } from '../src/ui/profile-presentation.js';

const delhi = { displayName: 'Aisha', city: 'Delhi', state: 'Delhi', country: 'India', latitude: 28.6139, longitude: 77.209, locationSource: 'test' };
async function setup() { const adapter = new IndexedDbAdapter({ name: `simple-${Math.random()}`, indexedDB: new IDBFactory() }); const repository = new RoutineRepository(adapter); await repository.initialize(); return { adapter, repository }; }

test('first-run profile requires a non-empty user name at the UI/domain boundary', () => { assert.throws(() => validateDisplayName('  '), /name is required/); assert.equal(validateDisplayName(' Aisha '), 'Aisha'); });
test('profile model includes identity, location, Firebase-ready timestamps and automatic settings', () => { const profile = createLocationProfile(delhi); for (const key of ['displayName', 'city', 'state', 'country', 'latitude', 'longitude', 'timeZone', 'placeId', 'formattedAddress', 'locationSource', 'createdAt', 'updatedAt']) assert.ok(key in profile); assert.equal(profile.madhab, 'Hanafi'); assert.equal(profile.calculationMethod, 'Karachi'); });
test('saved name drives heading and updates immediately after repository change', async () => { const { adapter, repository } = await setup(); await repository.saveLocationProfile(delhi, { warmCache: false }); const changed = await repository.saveDisplayName('Fatima'); assert.equal(profileHeading(changed), 'Fatima'); adapter.close(); });
test('city and state render below weekday with country fallback', () => { assert.equal(profileLocationLabel(delhi), 'Delhi, Delhi'); assert.equal(profileLocationLabel({ city: 'Dubai', state: '', country: 'United Arab Emirates' }), 'Dubai, United Arab Emirates'); });
test('India, UK, Gulf and unknown regions resolve automatic methods', () => { assert.equal(automaticCalculationMethod('India'), 'Karachi'); assert.equal(automaticCalculationMethod('United Kingdom'), 'MoonsightingCommittee'); assert.equal(automaticCalculationMethod('United Arab Emirates'), 'Dubai'); assert.equal(automaticCalculationMethod('Atlantis'), 'MuslimWorldLeague'); assert.equal(automaticPrayerSettings({ country: 'India' }).madhab, 'Hanafi'); assert.equal(automaticPrayerSettings({ country: 'United Kingdom' }).highLatitudeRule, 'recommended'); });
test('city search and map selection produce the shared location shape', async () => { const provider = new DevelopmentLocationProvider(); const city = (await provider.search('Del'))[0]; const mapped = mapLocationProfile(city); for (const value of [city, mapped]) for (const key of ['city', 'state', 'country', 'latitude', 'longitude', 'timeZone', 'locationSource']) assert.ok(key in value); });
test('development map selection uses the current location without network access', async () => { let selected; const container = { innerHTML: '', replaceChildren() {} }; await new DevelopmentMapProvider().mount({ container, initial: delhi, onChange: (value) => { selected = value; } }); assert.equal(selected.city, 'Delhi'); assert.equal(selected.timeZone, 'Asia/Kolkata'); });
test('location save forces Hanafi and the regional automatic method', async () => { const { adapter, repository } = await setup(); const saved = await repository.saveLocationProfile({ ...delhi, madhab: 'Shafi', calculationMethod: 'Egyptian' }, { warmCache: false }); assert.equal(saved.madhab, 'Hanafi'); assert.equal(saved.calculationMethod, 'Karachi'); adapter.close(); });
test('optional adjustments reset to automatic defaults', () => { assert.deepEqual(resetPrayerAdjustments(), { fajr: 0, sunrise: 0, dhuhr: 0, asr: 0, maghrib: 0, isha: 0 }); });
test('normal UI keeps optional adjustments collapsed and expert settings hidden', async () => { const html = await import('node:fs/promises').then(({ readFile }) => readFile(new URL('../index.html', import.meta.url), 'utf8')); assert.match(html, /<details id="optionalAdjustments">/); assert.doesNotMatch(html, /<label>Calculation method/); assert.match(html, /type="hidden"[^>]*id="profileHighLatitudeRule"|id="profileHighLatitudeRule"[^>]*type="hidden"/); });
