import './styles.css';
import { routineService } from './data/index.js';
import { calculateActivityProgress, calculateMonthlyProgress } from './data/progress.js';
import { addDays, APP_TIME_ZONE, isInRanges, isOnOrBefore, monthKey, todayIso } from './date-utils.js';
import { BrowserGeolocationProvider, createLocationProvider, resolveTimezone } from './location/providers.js';
import { DEFAULT_LOCATION_SUGGESTION, canActivateLocationDraft } from './location/location-model.js';
import { CALCULATION_METHODS, MADHABS, prayerSettingsFingerprint } from './prayer/prayer-calculator.js';
import { LocationAutocompleteController } from './location/autocomplete-controller.js';
import { saveLocationAndRefresh } from './location/location-save-flow.js';
import { WEEKDAY_KEYS, createSchedule, createTimeSlot } from './scheduling/schedule.js';
import { DailyLoadController } from './ui/daily-load-controller.js';
import { activityManagementControls } from './ui/activity-management-controls.js';

const state = { day: null, activities: [], fastingRanges: [], monthDays: [], activityDays: [], profile: null, editingSlots: [], progressToToday: true, activeView: 'home-view', locationDraft: { selected: null, coordinatesChanged: false }, locationResults: [] };
const $ = (id) => document.getElementById(id);
const searchProvider = createLocationProvider(); const geolocationProvider = new BrowserGeolocationProvider();
let dailyLoader; let autocompleteController;
const alarmActivity = (value) => value === 'fast' ? ['FAST_START', 'FAST_END'] : (state.activities.find(({ id }) => id === value)?.timeSlots || []).filter(({ enabled, notificationEnabled }) => enabled && notificationEnabled).map((slot) => `${state.activities.find(({ id }) => id === value).alarmId || `ACTIVITY:${value}`}:${slot.id}`);

function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]); }
function subtractMinutes(time, minutes) {
  const match = time?.match(/(\d+):(\d+)\s*(AM|PM)/i); if (!match) return null;
  let hour = Number(match[1]) % 12 + (match[3].toUpperCase() === 'PM' ? 12 : 0);
  const date = new Date(2000, 0, 1, hour, Number(match[2]) - minutes);
  return date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });
}
function timeMinutes(time) {
  if (!time) return 9998; const upper = time.toUpperCase();
  if (upper.includes('PRE-JUMMAH')) return 690; if (upper.includes('POST-GYM')) return 600; if (upper.includes('EVENING')) return 1200;
  const match = time.match(/(\d+):(\d+)\s*(AM|PM)?/i); if (!match) return 9998;
  let hour = Number(match[1]); if (match[3]?.toUpperCase() === 'PM' && hour < 12) hour += 12; if (match[3]?.toUpperCase() === 'AM' && hour === 12) hour = 0;
  return hour * 60 + Number(match[2]);
}
function setRing(ringId, textId, percent) {
  const color = percent >= 100 ? '#3b82f6' : percent >= 80 ? '#22c55e' : percent >= 50 ? '#eab308' : '#ef4444';
  $(ringId).style.background = `conic-gradient(${color} ${percent}%, #e2e8f0 0%)`; $(textId).textContent = `${percent}%`; $(textId).style.color = color;
}
function alarmEnabled(day, id) { const base = id.split(':')[0]; return day.alarmsEnabled && !day.disabledAlarmIds.includes(id) && !day.disabledAlarmIds.includes(base); }
function isRamadan(date) { return isInRanges(date, state.fastingRanges); }
function isFastingDay(day) { return day.weekday === 'Friday' || isRamadan(day.date); }

function renderDay() {
  const day = state.day; if (!day?.date || !Array.isArray(day.occurrences)) throw new Error('Cannot render an invalid daily routine record.'); $('dayOfWeek').textContent = day.weekday;
  $('dailyAlarmText').style.color = day.alarmsEnabled ? '#166534' : '#ef4444'; $('dailyAlarmIcon').textContent = day.alarmsEnabled ? '🔔' : '🔕';
  const rows = [...day.occurrences].sort((a, b) => {
    if (a.activityId === 'wake-up') return -1; if (b.activityId === 'wake-up') return 1; if (a.activityId === 'sleep') return 1; if (b.activityId === 'sleep') return -1; return timeMinutes(a.time) - timeMinutes(b.time);
  });
  $('routine-list').innerHTML = rows.map((occurrence) => {
    const timing = occurrence.notificationEnabled ? `<button class="${alarmEnabled(day, occurrence.notificationId) ? 'timing-alarm-on' : 'timing-alarm-off'}" data-alarm="${occurrence.notificationId}">${escapeHtml(occurrence.time)}</button>` : `<span class="timing-no-alarm">${escapeHtml(occurrence.time)}</span>`;
    const name = occurrence.label ? `${occurrence.activityName} · ${occurrence.label}` : occurrence.activityName;
    return `<div class="routine-item"><div>${timing}</div><div class="activity-name">${escapeHtml(name)}</div><div class="status"><input type="checkbox" data-completion="${occurrence.id}" aria-label="Complete ${escapeHtml(name)}" ${day.completions[occurrence.id] ? 'checked' : ''}></div></div>`;
  }).join('');
  const enabledFast = (id) => alarmEnabled(day, id) ? 'timing-alarm-on' : 'timing-alarm-off';
  const fastActive = isFastingDay(day);
  const prayers = day.prayerTimes || {}; const fajr = prayers.fajrStart || prayers.fastStart || 'N/A', sunrise = prayers.fajrEnd || prayers.sunrise || 'N/A', maghrib = prayers.fastEnd || prayers.maghrib || 'N/A';
  $('fajr-display').innerHTML = `Fajr Time: <span class="timing-no-alarm">${fajr}</span> - <span class="timing-no-alarm">${sunrise}</span>`;
  $('fast-display').innerHTML = fastActive ? `Fast Time: <button class="${enabledFast('FAST_START')}" data-alarm="FAST_START">${fajr}</button> - <button class="${enabledFast('FAST_END')}" data-alarm="FAST_END">${maghrib}</button>` : `Fast Time: <span class="timing-no-alarm">${fajr}</span> - <span class="timing-no-alarm">${maghrib}</span>`;
  $('bottom-timings').hidden = false; calculateDailyProgress();
}
function calculateDailyProgress() { const boxes = [...document.querySelectorAll('[data-completion]')]; setRing('dailyProgressRing', 'dailyProgressText', boxes.length ? Math.round(boxes.filter((box) => box.checked).length / boxes.length * 100) : 0); }
function validIsoDate(value) { return /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(new Date(`${value}T12:00:00+05:30`).getTime()); }
function setDailyLoading(loading) { $('previousDate').disabled = loading; $('nextDate').disabled = loading; $('datePicker').disabled = loading; $('dailyAlarmToggle').disabled = loading; }
function showDailyError(error, date) { state.day = null; $('dayOfWeek').textContent = ''; $('bottom-timings').hidden = true; setRing('dailyProgressRing', 'dailyProgressText', 0); $('routine-list').innerHTML = `<div class="routine-error"><strong>Unable to load routine for ${escapeHtml(date)}.</strong><p>${escapeHtml(error?.message || 'Unexpected database error.')}</p><button class="home-btn" type="button" data-retry-routine>Retry</button></div>`; }
async function fetchRoutine() { const date = $('datePicker').value; if (!validIsoDate(date)) { showDailyError(new Error('Select a valid date.'), date || 'the selected date'); return null; } return dailyLoader.load(date); }
function requireCurrentDay(action) { const ready = dailyLoader?.getReadyDay(); if (!ready?.date || state.day?.date !== ready.date) { console.warn(`Ignored ${action}: daily routine is not ready.`); return null; } return ready; }

function activityCell(day, activity) { const occurrences = day.occurrences.filter(({ activityId }) => activityId === activity.id); return occurrences.length ? occurrences.map((item) => `<input type="checkbox" class="grid-checkbox" title="${escapeHtml(item.time)}" ${day.completions[item.id] ? 'checked' : ''} disabled>`).join(' ') : '-'; }
function relevantForProgress(day) { return !state.progressToToday || isOnOrBefore(day.date, todayIso()); }
function renderMonthly() {
  const columns = [...new Map(state.monthDays.flatMap(({ activities }) => activities).map((activity) => [activity.id, activity])).values()].sort((a, b) => a.order - b.order);
  const progress = calculateMonthlyProgress(state.monthDays, state.progressToToday ? todayIso() : null);
  $('monthly-table').innerHTML = `<thead><tr><th>Date</th><th>Day</th>${columns.map(({ name }) => `<th>${escapeHtml(name)}</th>`).join('')}</tr></thead><tbody>${state.monthDays.map((day) => `<tr><td class="${day.alarmsEnabled ? 'date-alarm-on' : 'date-alarm-off'}" data-month-date="${day.date}">${day.date}</td><td>${day.weekday}</td>${columns.map((activity) => `<td>${day.activities.some(({ id }) => id === activity.id) ? activityCell(day, activity) : '-'}</td>`).join('')}</tr>`).join('')}</tbody>`;
  const allOff = state.monthDays.every((day) => !day.alarmsEnabled); $('monthlyAlarmTitle').textContent = `Monthly Progress ${allOff ? '🔕' : '🔔'}`; $('monthlyAlarmTitle').style.color = allOff ? '#ef4444' : '#166534';
  setRing('monthlyProgressRing', 'monthlyProgressText', progress.percent); $('monthly-status').textContent = `Completed ${progress.completed} out of ${progress.possible} activities ${state.progressToToday ? '(Up to Today)' : '(Total for Month)'}.`;
}
async function fetchMonthly() { $('monthly-status').textContent = 'Loading monthly data...'; state.monthDays = await routineService.ensureMonth($('monthPicker').value); renderMonthly(); }

function visibleActivityDays() {
  const type = $('activityViewType').value; if (type !== 'weekly') return state.activityDays;
  const week = Number($('actWeekPicker').value); return state.activityDays.filter((day) => { const number = Number(day.date.slice(-2)); return week < 5 ? number >= (week - 1) * 7 + 1 && number <= week * 7 : number >= 29; });
}
function renderActivity() {
  const id = $('activitySelector').value; const activity = state.activities.find((item) => item.id === id); const isFast = id === 'fast'; const days = visibleActivityDays(); const alarmIds = alarmActivity(id);
  const body = days.map((day) => {
    let value;
    if (isFast) { value = `${day.prayerTimes.fastStart} - ${day.prayerTimes.fastEnd}`; }
    else { value = day.occurrences.some((item) => item.activityId === id) ? activityCell(day, activity) : '-'; }
    const supported = alarmIds.length && (!isFast || isFastingDay(day)); const off = supported && alarmIds.every((alarmId) => !alarmEnabled(day, alarmId));
    return `<tr><td class="${supported ? (off ? 'date-alarm-off' : 'date-alarm-on') : 'date-no-alarm'}" ${supported ? `data-activity-date="${day.date}"` : ''}>${day.date}</td><td>${day.weekday}</td><td><span class="${isFast ? 'timing-no-alarm' : ''}">${value}</span></td></tr>`;
  }).join('');
  const progress = isFast ? { completed: 1, possible: 1, percent: 100 } : calculateActivityProgress(days, id, state.progressToToday ? todayIso() : null);
  $('activity-table').innerHTML = `<thead><tr><th>Date</th><th>Day</th><th>${escapeHtml(isFast ? 'Fast (Start & End)' : activity.name)}</th></tr></thead><tbody>${body}</tbody>`;
  const canAlarm = alarmIds.length > 0; const allOff = canAlarm && days.filter((day) => !isFast || isFastingDay(day)).every((day) => alarmIds.every((alarmId) => !alarmEnabled(day, alarmId)));
  $('activityAlarmTitle').className = `clickable-title${canAlarm ? ' active' : ''}`; $('activityAlarmTitle').textContent = `Activity Progress${canAlarm ? ` ${allOff ? '🔕' : '🔔'}` : ''}`; $('activityAlarmTitle').style.color = allOff ? '#ef4444' : '#166534';
  setRing('activityProgressRing', 'activityProgressText', progress.percent); $('activity-status').textContent = isFast ? 'Displaying Fast times for selected period.' : `Completed ${progress.completed} times out of ${progress.possible} applicable days ${state.progressToToday ? '(Up to Today)' : '(Total for Period)'}.`;
}
async function fetchActivity() { $('activity-status').textContent = 'Loading activity data...'; state.activityDays = $('activityViewType').value === 'yearly' ? await routineService.getYear($('actYearPicker').value) : await routineService.ensureMonth($('actMonthPicker').value); renderActivity(); }
function updateActivityControls() { const type = $('activityViewType').value; $('actMonthPicker').hidden = type === 'yearly'; $('actWeekPicker').hidden = type !== 'weekly'; $('actYearPicker').hidden = type !== 'yearly'; fetchActivity(); }
function showView(viewId) { state.activeView = viewId; document.querySelectorAll('.view-section').forEach((section) => section.classList.toggle('active', section.id === viewId)); $('home-controls').hidden = viewId !== 'home-view'; $('dropdownMenu').classList.remove('show'); if (viewId === 'monthly-view') { $('monthPicker').value = monthKey($('datePicker').value); fetchMonthly(); } if (viewId === 'activity-view') { $('actMonthPicker').value = monthKey($('datePicker').value); $('actYearPicker').value = $('datePicker').value.slice(0, 4); updateActivityControls(); } if (viewId === 'manage-view') renderManagement(); if (viewId === 'settings-view') renderSettings(); }

function activityOptions(selected = $('activitySelector').value) {
  const options = state.activities.map(({ id, name }, index) => `${index === 3 ? '<option value="fast">Fast (Start & End)</option>' : ''}<option value="${id}">${escapeHtml(name)}</option>`).join('');
  $('activitySelector').innerHTML = options; if ([...$('activitySelector').options].some(({ value }) => value === selected)) $('activitySelector').value = selected;
}
async function refreshDefinitions() { state.activities = await routineService.getActivities({ includeDisabled: false }); state.fastingRanges = await routineService.getFastingRanges(); activityOptions(); }
function displayTimeForInput(time) { const match = time?.match(/(\d+):(\d+)\s*(AM|PM)/i); if (!match) return time || ''; let hour = Number(match[1]) % 12 + (match[3].toUpperCase() === 'PM' ? 12 : 0); return `${String(hour).padStart(2, '0')}:${match[2]}`; }
function displayTimeForRoutine(time) { if (!time) return ''; const [hourValue, minutes] = time.split(':').map(Number); const suffix = hourValue >= 12 ? 'PM' : 'AM'; return `${hourValue % 12 || 12}:${String(minutes).padStart(2, '0')} ${suffix}`; }
function renderScheduleFields() { const type = $('scheduleType').value; $('weekdayFields').hidden = !['selected-weekdays', 'weekly'].includes(type); $('weeklyFields').hidden = type !== 'weekly'; $('monthlyFields').hidden = type !== 'monthly'; $('yearlyFields').hidden = type !== 'yearly'; $('specificDateFields').hidden = type !== 'specific-date'; $('specificDatesFields').hidden = type !== 'specific-dates'; $('rangeFields').hidden = type !== 'date-range'; }
function renderTimeSlots() { $('timeSlotEditor').innerHTML = state.editingSlots.map((slot, index) => `<div class="time-slot-row" data-slot-index="${index}"><input type="time" data-slot-field="time" value="${displayTimeForInput(slot.time)}" aria-label="Time"><input type="text" data-slot-field="label" value="${escapeHtml(slot.label)}" placeholder="Label (optional)"><button class="nav-action danger" type="button" data-slot-action="remove">Remove</button><div class="slot-options"><label><input type="checkbox" data-slot-field="enabled" ${slot.enabled ? 'checked' : ''}> Enabled</label><label><input type="checkbox" data-slot-field="notificationEnabled" ${slot.notificationEnabled ? 'checked' : ''}> Notification</label><label>Offset <input type="number" data-slot-field="notificationOffsetMinutes" value="${slot.notificationOffsetMinutes}" step="1"> min</label><button type="button" class="nav-action" data-slot-action="up" ${index === 0 ? 'disabled' : ''}>↑</button><button type="button" class="nav-action" data-slot-action="down" ${index === state.editingSlots.length - 1 ? 'disabled' : ''}>↓</button></div></div>`).join(''); }
function readSchedule() { const type = $('scheduleType').value; return createSchedule({ type, weekdays: [...document.querySelectorAll('[name="scheduleWeekday"]:checked')].map(({ value }) => value), intervalWeeks: $('intervalWeeks').value, anchorDate: $('scheduleAnchor').value || null, dayOfMonth: $('monthlyDay').value, month: $('yearlyMonth').value, day: $('yearlyDay').value, date: $('specificDate').value || null, dates: $('specificDates').value.split(',').map((item) => item.trim()).filter(Boolean), startDate: $('rangeStart').value || null, endDate: $('rangeEnd').value || null }); }
function writeSchedule(schedule) { $('scheduleType').value = schedule.type; document.querySelectorAll('[name="scheduleWeekday"]').forEach((box) => { box.checked = schedule.weekdays.includes(box.value); }); $('intervalWeeks').value = schedule.intervalWeeks; $('scheduleAnchor').value = schedule.anchorDate || ''; $('monthlyDay').value = schedule.dayOfMonth || 1; $('yearlyMonth').value = schedule.month || 1; $('yearlyDay').value = schedule.day || 1; $('specificDate').value = schedule.date || ''; $('specificDates').value = schedule.dates.join(', '); $('rangeStart').value = schedule.startDate || ''; $('rangeEnd').value = schedule.endDate || ''; renderScheduleFields(); }
function resetActivityForm() { $('activityForm').reset(); $('activityForm').hidden = false; $('editActivityId').value = ''; $('activityEnabled').checked = true; state.editingSlots = [createTimeSlot({ id: `slot-${Date.now()}`, enabled: true })]; writeSchedule(createSchedule()); renderTimeSlots(); $('saveActivity').textContent = 'Add Activity'; $('cancelActivityEdit').hidden = true; }
function scheduleSummary(schedule) { return ({ daily: 'Every day', 'selected-weekdays': schedule.weekdays.join(', '), weekly: `Every ${schedule.intervalWeeks} week(s): ${schedule.weekdays.join(', ')}`, monthly: `Monthly on day ${schedule.dayOfMonth}`, yearly: `Yearly on ${schedule.month}/${schedule.day}`, 'specific-date': schedule.date, 'specific-dates': `${schedule.dates.length} specific dates`, 'date-range': `${schedule.startDate} to ${schedule.endDate}`, none: 'No recurring schedule' })[schedule.type]; }
async function renderManagement(message = '') {
  const activities = await routineService.getActivities(); state.activities = activities.filter(({ enabled }) => enabled); activityOptions();
  $('management-status').textContent = message;
  const current = state.day || await routineService.getDay($('datePicker').value);
  $('activity-management-list').innerHTML = activities.map((activity, index) => {
    const occurrence = current?.occurrences?.find(({ activityId }) => activityId === activity.id); const actions = activityManagementControls(activity, index, activities.length);
    return `<div class="management-item${activity.enabled ? '' : ' disabled'}${activity.protected ? ' protected-activity' : ''}"><div><div class="management-name">${activity.protected ? '<span aria-label="Locked">🔒</span> ' : ''}${escapeHtml(activity.name)}</div><div class="management-meta">${activity.protected ? `Prayer-controlled timing${occurrence?.time ? ` · ${escapeHtml(occurrence.time)}` : ''}` : `${escapeHtml(scheduleSummary(activity.schedule))} · ${activity.timeSlots.length} time slot(s)`}</div></div><div>${activity.enabled ? 'Enabled' : 'Disabled'}</div><div class="management-actions">${actions}</div></div>`;
  }).join('');
}
function fillLocationForm(profile, { selected = true } = {}) { $('profilePlaceId').value = profile.placeId || ''; $('profileFormattedAddress').value = profile.formattedAddress || ''; $('profileCity').value = profile.city || ''; $('profileState').value = profile.state || ''; $('profileCountry').value = profile.country || ''; $('profileLatitude').value = profile.latitude ?? ''; $('profileLongitude').value = profile.longitude ?? ''; $('profileTimezone').value = profile.timeZone || resolveTimezone(profile.latitude, profile.longitude); $('profileMethod').value = profile.calculationMethod || 'Karachi'; $('profileMadhab').value = profile.madhab || 'Hanafi'; $('profileSehriOffset').value = profile.sehriOffsetMinutes ?? 30; document.querySelectorAll('[data-adjustment]').forEach((input) => { input.value = profile.adjustments?.[input.dataset.adjustment] || 0; }); state.locationDraft = { selected: selected ? structuredClone(profile) : null, coordinatesChanged: false }; }
function renderSettings() { const profile = state.profile || DEFAULT_LOCATION_SUGGESTION; $('location-summary').innerHTML = `<p>${escapeHtml(profile.city)}, ${escapeHtml(profile.state)}, ${escapeHtml(profile.country)}</p><p>${profile.latitude}, ${profile.longitude} · ${escapeHtml(profile.timeZone)}</p><p>${escapeHtml(profile.calculationMethod)} · ${escapeHtml(profile.madhab)}</p>`; }
function openLocationSetup(editing = false) { const profile = state.profile || DEFAULT_LOCATION_SUGGESTION; fillLocationForm(profile); $('locationSearch').value = profile.city; $('locationProviderLabel').textContent = searchProvider.label; $('locationProviderMessage').textContent = searchProvider.mode === 'mock' ? searchProvider.developmentMessage : ''; $('cancelLocation').hidden = !editing; $('menuButton').hidden = !editing; showView('location-view'); }
function readLocationForm() { if (!canActivateLocationDraft({ selectedPlace: state.locationDraft.selected, coordinatesChanged: state.locationDraft.coordinatesChanged })) throw new Error('Select a city suggestion or confirm validated manual coordinates.'); return { placeId: $('profilePlaceId').value || null, formattedAddress: $('profileFormattedAddress').value, displayName: $('profileCity').value, city: $('profileCity').value, state: $('profileState').value, country: $('profileCountry').value, latitude: $('profileLatitude').value, longitude: $('profileLongitude').value, timeZone: $('profileTimezone').value, calculationMethod: $('profileMethod').value, madhab: $('profileMadhab').value, sehriOffsetMinutes: $('profileSehriOffset').value, adjustments: Object.fromEntries([...document.querySelectorAll('[data-adjustment]')].map((input) => [input.dataset.adjustment, Number(input.value) || 0])), locationSource: state.locationDraft.selected?.locationSource || 'manual-coordinates' }; }

function renderLocationResults(searchState) { state.locationResults = searchState.results; $('locationSearch').setAttribute('aria-expanded', String(['results', 'fallback', 'loading', 'empty', 'error'].includes(searchState.status))); const buttons = () => searchState.results.map((item, index) => `<button class="location-result${index === searchState.activeIndex ? ' active' : ''}" role="option" aria-selected="${index === searchState.activeIndex}" type="button" data-location-index="${index}"><strong>${escapeHtml(item.displayName || item.city || item.label)}</strong><span>${escapeHtml(item.secondaryText || [item.state, item.country].filter(Boolean).join(', '))}</span></button>`).join(''); if (searchState.status === 'loading') $('locationResults').innerHTML = '<p class="summary">Searching cities…</p>'; else if (searchState.status === 'empty') $('locationResults').innerHTML = `<p class="summary">${searchProvider.mode === 'mock' ? 'No matching development locations' : 'No matching cities found.'}</p>`; else if (searchState.status === 'error') $('locationResults').innerHTML = `<p class="summary location-error">${escapeHtml(searchState.error?.message || 'City search failed. Please retry.')}</p>`; else if (searchState.status === 'fallback') $('locationResults').innerHTML = `<p class="summary location-error">${escapeHtml(searchState.error.message)} Showing ${escapeHtml(searchState.fallbackLabel)}.</p>${buttons()}`; else $('locationResults').innerHTML = buttons(); }
async function selectLocationResult(item) { $('location-status').textContent = 'Resolving selected city…'; try { const location = item.latitude != null ? item : await searchProvider.details(item.placeId); fillLocationForm({ ...DEFAULT_LOCATION_SUGGESTION, ...location }); $('locationSearch').value = location.displayName || location.city; autocompleteController.escape(); $('location-status').textContent = 'City selected. Review the details and confirm to activate it.'; } catch (error) { console.error('Place resolution failed.', error); $('location-status').textContent = `Unable to resolve this city: ${error.message}`; } }
function updatePrayerDiagnostics() { if (!import.meta.env.DEV || !state.profile) return; const cache = routineService.prayerCache.lastResult; $('prayerDiagnostics').hidden = false; $('prayerDiagnostics').textContent = `Development diagnostics — coordinates: ${state.profile.latitude}, ${state.profile.longitude}; timezone: ${state.profile.timeZone}; method: ${state.profile.calculationMethod}; madhab: ${state.profile.madhab}; fingerprint: ${prayerSettingsFingerprint(state.profile)}; timing source: ${cache?.source || 'not loaded'}.`; }

function bindEvents() {
  $('menuButton').addEventListener('click', (event) => { event.stopPropagation(); const open = $('dropdownMenu').classList.toggle('show'); $('menuButton').setAttribute('aria-expanded', String(open)); }); document.addEventListener('click', () => $('dropdownMenu').classList.remove('show'));
  document.querySelectorAll('[data-view]').forEach((button) => button.addEventListener('click', () => showView(button.dataset.view)));
  $('datePicker').addEventListener('change', fetchRoutine); $('previousDate').addEventListener('click', () => { if (!validIsoDate($('datePicker').value)) return; $('datePicker').value = addDays($('datePicker').value, -1); fetchRoutine(); }); $('nextDate').addEventListener('click', () => { if (!validIsoDate($('datePicker').value)) return; $('datePicker').value = addDays($('datePicker').value, 1); fetchRoutine(); });
  $('dailyAlarmToggle').addEventListener('click', async () => { const day = requireCurrentDay('daily alarm toggle'); if (!day) return; await routineService.setDayAlarms(day.date, !day.alarmsEnabled); await fetchRoutine(); });
  $('routine-list').addEventListener('change', async ({ target }) => { if (!target.dataset.completion) return; const day = requireCurrentDay('completion update'); if (!day) return; await routineService.setCompletion(day.date, target.dataset.completion, target.checked); if (state.day?.date !== day.date) return; state.day.completions[target.dataset.completion] = target.checked; calculateDailyProgress(); });
  $('home-view').addEventListener('click', async ({ target }) => { if (target.hasAttribute('data-retry-routine')) { await fetchRoutine(); return; } const alarmId = target.dataset.alarm; if (!alarmId) return; const day = requireCurrentDay('individual alarm toggle'); if (!day) return; await routineService.setAlarm(day.date, alarmId, !alarmEnabled(day, alarmId)); if (state.day?.date === day.date) await fetchRoutine(); });
  $('monthPicker').addEventListener('change', fetchMonthly); $('monthlyProgressRing').addEventListener('click', () => { state.progressToToday = !state.progressToToday; renderMonthly(); });
  $('monthlyAlarmTitle').addEventListener('click', async () => { const enable = state.monthDays.every((day) => !day.alarmsEnabled); const ids = [...new Set(state.monthDays.flatMap(({ occurrences }) => occurrences.filter(({ notificationEnabled }) => notificationEnabled).map(({ notificationId }) => notificationId)).concat(['FAST_START', 'FAST_END']))]; await routineService.setManyAlarms(state.monthDays, ids, enable); await fetchMonthly(); });
  $('monthly-table').addEventListener('click', async ({ target }) => { if (!target.dataset.monthDate) return; const day = state.monthDays.find(({ date }) => date === target.dataset.monthDate); await routineService.setDayAlarms(day.date, !day.alarmsEnabled); await fetchMonthly(); });
  $('activitySelector').addEventListener('change', renderActivity); $('activityViewType').addEventListener('change', updateActivityControls); $('actMonthPicker').addEventListener('change', fetchActivity); $('actWeekPicker').addEventListener('change', renderActivity); $('actYearPicker').addEventListener('change', fetchActivity); $('activityProgressRing').addEventListener('click', () => { state.progressToToday = !state.progressToToday; renderActivity(); });
  $('activityAlarmTitle').addEventListener('click', async () => { const ids = alarmActivity($('activitySelector').value); if (!ids.length) return; const days = visibleActivityDays().filter((day) => $('activitySelector').value !== 'fast' || isFastingDay(day)); const enable = days.every((day) => ids.every((id) => !alarmEnabled(day, id))); await routineService.setManyAlarms(days, ids, enable); await fetchActivity(); });
  $('activity-table').addEventListener('click', async ({ target }) => { if (!target.dataset.activityDate) return; const day = state.activityDays.find(({ date }) => date === target.dataset.activityDate); const ids = alarmActivity($('activitySelector').value); const enable = ids.every((id) => !alarmEnabled(day, id)); await routineService.setManyAlarms([day], ids, enable); await fetchActivity(); });
  $('scheduleType').addEventListener('change', renderScheduleFields);
  $('addTimeSlot').addEventListener('click', () => { state.editingSlots.push(createTimeSlot({ id: `slot-${Date.now()}-${state.editingSlots.length}`, enabled: true })); renderTimeSlots(); });
  $('timeSlotEditor').addEventListener('change', ({ target }) => { const row = target.closest('[data-slot-index]'); if (!row || !target.dataset.slotField) return; const slot = state.editingSlots[Number(row.dataset.slotIndex)], field = target.dataset.slotField; slot[field] = target.type === 'checkbox' ? target.checked : field === 'time' ? displayTimeForRoutine(target.value) : field === 'notificationOffsetMinutes' ? Number(target.value) : target.value; });
  $('timeSlotEditor').addEventListener('click', ({ target }) => { const row = target.closest('[data-slot-index]'), action = target.dataset.slotAction; if (!row || !action) return; const index = Number(row.dataset.slotIndex); if (action === 'remove') state.editingSlots.splice(index, 1); if (action === 'up') [state.editingSlots[index - 1], state.editingSlots[index]] = [state.editingSlots[index], state.editingSlots[index - 1]]; if (action === 'down') [state.editingSlots[index + 1], state.editingSlots[index]] = [state.editingSlots[index], state.editingSlots[index + 1]]; renderTimeSlots(); });
  $('activityForm').addEventListener('submit', async (event) => { event.preventDefault(); if (!state.editingSlots.length) throw new Error('Add at least one time slot.'); const values = { name: $('activityName').value, enabled: $('activityEnabled').checked, schedule: readSchedule(), timeSlots: state.editingSlots }; const id = $('editActivityId').value; if (id) await routineService.editActivity(id, values); else await routineService.addActivity(values); resetActivityForm(); await renderManagement(id ? 'Activity updated.' : 'Activity added.'); });
  $('cancelActivityEdit').addEventListener('click', resetActivityForm);
  $('activity-management-list').addEventListener('click', async ({ target }) => { const action = target.dataset.manage, id = target.dataset.id; if (!action || !id) return; const activities = await routineService.getActivities(); const activity = activities.find((item) => item.id === id); if (action === 'edit') { if (activity.protected) return; $('editActivityId').value = id; $('activityName').value = activity.name; $('activityEnabled').checked = activity.enabled; state.editingSlots = cloneSlots(activity.timeSlots); writeSchedule(activity.schedule); renderTimeSlots(); $('saveActivity').textContent = 'Save Changes'; $('cancelActivityEdit').hidden = false; return; } if (action === 'toggle') await routineService.editActivity(id, { enabled: !activity.enabled }); if (action === 'notification') await routineService.editActivity(id, { timeSlots: activity.timeSlots.map((slot) => ({ ...slot, notificationEnabled: !activity.timeSlots.some((item) => item.notificationEnabled) })) }); if (action === 'remove') await routineService.softDeleteActivity(id); if (action === 'up' || action === 'down') { const swap = activities.findIndex((item) => item.id === id) + (action === 'up' ? -1 : 1); const ids = activities.map((item) => item.id); [ids[ids.indexOf(id)], ids[swap]] = [ids[swap], id]; await routineService.reorderActivities(ids); } await renderManagement('Activity list updated.'); });
  $('changeLocation').addEventListener('click', () => openLocationSetup(true)); $('cancelLocation').addEventListener('click', () => showView('settings-view'));
  $('detectLocation').addEventListener('click', async () => { $('location-status').textContent = 'Detecting location…'; try { const coordinates = await geolocationProvider.detect(); const named = await searchProvider.reverseGeocode(coordinates); fillLocationForm({ ...DEFAULT_LOCATION_SUGGESTION, ...named, ...coordinates, timeZone: resolveTimezone(coordinates.latitude, coordinates.longitude), placeId: named.placeId || null, locationSource: 'device-foreground' }); $('location-status').textContent = 'Location detected. Review and confirm.'; } catch (error) { $('location-status').textContent = `${error.message} Use city search or validated manual coordinates below.`; } });
  $('locationSearch').addEventListener('input', ({ target }) => { state.locationDraft.selected = null; autocompleteController.input(target.value); });
  $('locationSearch').addEventListener('keydown', (event) => { if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); autocompleteController.move(event.key === 'ArrowDown' ? 1 : -1); } else if (event.key === 'Enter') { const item = autocompleteController.current(); if (item) { event.preventDefault(); void selectLocationResult(item); } } else if (event.key === 'Escape') autocompleteController.escape(); });
  $('locationResults').addEventListener('click', ({ target }) => { const button = target.closest('[data-location-index]'); if (!button) return; void selectLocationResult(state.locationResults[Number(button.dataset.locationIndex)]); });
  document.addEventListener('click', ({ target }) => { if (!target.closest('.location-search') && !target.closest('#locationResults')) autocompleteController?.escape(); });
  ['profileCity', 'profileState', 'profileCountry'].forEach((id) => $(id).addEventListener('input', () => { state.locationDraft.selected = null; $('profilePlaceId').value = ''; }));
  ['profileLatitude', 'profileLongitude'].forEach((id) => $(id).addEventListener('input', () => { try { const latitude = Number($('profileLatitude').value), longitude = Number($('profileLongitude').value); if (latitude < -90 || latitude > 90) throw new Error('Latitude must be between -90 and 90.'); if (longitude < -180 || longitude > 180) throw new Error('Longitude must be between -180 and 180.'); if (!Number.isFinite(latitude) || !Number.isFinite(longitude)) return; $('profileTimezone').value = resolveTimezone(latitude, longitude); $('profilePlaceId').value = ''; state.locationDraft = { selected: null, coordinatesChanged: true }; $('location-status').textContent = 'Manual coordinates validated. Review and confirm.'; } catch (error) { state.locationDraft.coordinatesChanged = false; $('location-status').textContent = error.message; } }));
  $('locationForm').addEventListener('submit', async (event) => { event.preventDefault(); const submit = event.submitter || $('locationForm').querySelector('[type="submit"]'); submit.disabled = true; $('location-status').textContent = 'Saving location and regenerating prayer timings…'; try { const draft = readLocationForm(); const result = await saveLocationAndRefresh({ repository: routineService, draft, currentDate: todayIso(), refreshHome: async () => { state.monthDays = []; state.activityDays = []; $('menuButton').hidden = false; await refreshDefinitions(); showView('home-view'); await fetchRoutine(); } }); state.profile = result.profile; updatePrayerDiagnostics(); if (import.meta.env.DEV) { const diagnostic = result.diagnostics; $('locationSaveDiagnostics').hidden = false; $('locationSaveDiagnostics').textContent = `Location updated — ${diagnostic.coordinates.latitude}, ${diagnostic.coordinates.longitude}; ${diagnostic.timeZone}; fingerprint ${String(diagnostic.oldFingerprint || 'none').slice(0, 18)} → ${String(diagnostic.newFingerprint).slice(0, 18)}; ${diagnostic.regeneratedPrayerRecords} prayer records regenerated; Home refreshed: ${diagnostic.homeRefreshed ? 'yes' : 'no'}.`; setTimeout(() => { $('locationSaveDiagnostics').hidden = true; }, 15000); } $('location-status').textContent = 'Location and prayer timings updated successfully.'; } catch (error) { console.error('Location profile save failed.', error); $('location-status').textContent = `Unable to save location: ${error.message}. Your previous location remains active. Retry when ready.`; } finally { submit.disabled = false; } });
}

function initialiseControls() {
  autocompleteController = new LocationAutocompleteController({ provider: searchProvider, onState: renderLocationResults });
  $('weekdayChoices').innerHTML = WEEKDAY_KEYS.map((day) => `<label><input type="checkbox" name="scheduleWeekday" value="${day}">${day.slice(0, 3)}</label>`).join('');
  $('profileMethod').innerHTML = CALCULATION_METHODS.map((method) => `<option value="${method}">${method}</option>`).join(''); $('profileMadhab').innerHTML = MADHABS.map((madhab) => `<option value="${madhab}">${madhab}</option>`).join('');
  $('prayerAdjustments').innerHTML = ['fajr', 'sunrise', 'dhuhr', 'asr', 'maghrib', 'isha'].map((prayer) => `<label>${prayer[0].toUpperCase() + prayer.slice(1)}<input type="number" data-adjustment="${prayer}" value="0" step="1"></label>`).join(''); resetActivityForm();
  const currentYear = Number(todayIso().slice(0, 4)); $('actYearPicker').innerHTML = Array.from({ length: 9 }, (_, index) => currentYear - 4 + index).map((year) => `<option value="${year}">${year}</option>`).join('');
  $('datePicker').value = todayIso(); $('monthPicker').value = monthKey(todayIso()); $('actMonthPicker').value = monthKey(todayIso()); $('actYearPicker').value = String(currentYear);
  setInterval(() => { $('clock').textContent = new Date().toLocaleTimeString('en-US', { timeZone: APP_TIME_ZONE, hour12: true }); }, 1000);
}

function cloneSlots(slots) { return structuredClone(slots); }
async function bootstrap() {
  initialiseControls();
  dailyLoader = new DailyLoadController({ repository: routineService, onLoading: (loading) => { setDailyLoading(loading); if (loading) { state.day = null; $('routine-list').innerHTML = '<i>Loading data...</i>'; $('bottom-timings').hidden = true; } }, onSuccess: (day) => { state.day = day; renderDay(); updatePrayerDiagnostics(); }, onError: showDailyError });
  bindEvents(); setDailyLoading(true);
  try {
    const initialization = await routineService.initialize(); if (import.meta.env.DEV) console.info('[development] IndexedDB diagnostics', initialization.diagnostics);
    await refreshDefinitions(); state.profile = await routineService.getLocationProfile();
    if (state.profile) { await fetchRoutine(); void routineService.warmPrayerCache(); } else { setDailyLoading(false); openLocationSetup(false); }
  } catch (error) { console.error('Application database initialization failed.', error); setDailyLoading(false); showView('home-view'); showDailyError(error, $('datePicker').value || 'the selected date'); }
}
await bootstrap();
