import { createUserWithEmailAndPassword, sendEmailVerification, signInWithEmailAndPassword, sendPasswordResetEmail, signOut, onAuthStateChanged, reload } from 'firebase/auth'; import { doc, getDoc, setDoc, serverTimestamp } from 'firebase/firestore'; import { evaluateAccountAccess } from './access-policy.js';
import { getFunctions, httpsCallable } from 'firebase/functions';
export class AuthService { constructor(services, { cache = globalThis.localStorage } = {}) { this.auth = services?.auth; this.firestore = services?.firestore; this.functions = services?.app ? getFunctions(services.app) : null; this.cache = cache; }
  waitForUser() { return new Promise((resolve) => { const unsubscribe = onAuthStateChanged(this.auth, (user) => { unsubscribe(); resolve(user); }); }); }
  async signup({ displayName, email, password, confirmPassword }) { if (!displayName?.trim()) throw new Error('Display name is required.'); if (password !== confirmPassword) throw new Error('Passwords do not match.'); const credential = await createUserWithEmailAndPassword(this.auth, email.trim(), password); await sendEmailVerification(credential.user); await setDoc(doc(this.firestore, 'users', credential.user.uid), { uid: credential.user.uid, displayName: displayName.trim(), email: credential.user.email, emailVerified: false, role: 'user', accountStatus: 'pending', subscriptionStatus: 'trial', subscriptionStart: serverTimestamp(), subscriptionEnd: null, createdAt: serverTimestamp(), updatedAt: serverTimestamp(), lastLoginAt: serverTimestamp(), prayerRoutineEnabled: true }); return credential.user; }
  async login(email, password) { return (await signInWithEmailAndPassword(this.auth, email.trim(), password)).user; } resetPassword(email) { return sendPasswordResetEmail(this.auth, email.trim()); } logout() { return signOut(this.auth); }
  async access(user) { await reload(user); if (!user.emailVerified) return { allowed: false, reason: 'email-unverified' }; const snapshot = await getDoc(doc(this.firestore, 'users', user.uid)); const record = snapshot.data(); const cachedAt = Date.now(); this.cache?.setItem('moin-access-cache', JSON.stringify({ uid: user.uid, record, cachedAt })); return { ...evaluateAccountAccess(record, { online: true, cachedAt }), record }; }
  cachedAccess(user) { try { const cached = JSON.parse(this.cache?.getItem('moin-access-cache')); if (cached?.uid !== user.uid) return { allowed: false, reason: 'reconnect-required' }; return { ...evaluateAccountAccess(cached.record, { online: false, cachedAt: cached.cachedAt }), record: cached.record }; } catch { return { allowed: false, reason: 'reconnect-required' }; } }
  async requestAccountDeletion() { return (await httpsCallable(this.functions, 'requestAccountDeletion')()).data; }
}
